spring.application.name=hr

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Springdoc / Swagger
springdoc.api-docs.path=/apis/v1/api-docs

# JWT
jwt.secret=hr-application-secret-key-must-be-at-least-256-bits!!
jwt.access-token-expiration=900000

